### ISSUE TITLE
Change it to an unbounded Queue

### ISSUE THREAD

**Issue by saini** [marufzaber/AdaptiveCC#2]
https://github.com/marufzaber/AdaptiveCC/blob/5bf54377eedaf43df136c0e5980c54f8fb2302a0/clone-detector/src/com/mondego/models/ThreadedChannel.java#L54

Please use an unbounded queue. 
The bounded queues can cause issues: 
From https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ThreadPoolExecutor.html
> Any BlockingQueue may be used to transfer and hold submitted tasks. The use of this queue interacts with pool sizing:
> If fewer than corePoolSize threads are running, the Executor always prefers adding a new thread rather than queuing.
> If corePoolSize or more threads are running, the Executor always prefers queuing a request rather than adding a new thread.
> If a request cannot be queued, a new thread is created unless this would exceed maximumPoolSize, in which case, the task will be rejected.

**Comment by marufzaber** [comment]
Updated!
